name: Shell Commands 

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
        timeout-minutes: 0
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: python Command 
        run: |
          import platform 
          print
          (platform.processor())
        shell: python # you can use difference sripting languages to run commands under specific VMs. For Compatibility: Check https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-a-specific-shell for details. need shell: for the python code to run
  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"] #this needs commands ensures that jobs take place sequentially, otherwise they run parallel
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash 
